config/routes.rb
Rails.application.routes.draw do
  resources :most_ranked_posts
  resources :profiles
  resources :posts
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/most_ranked_post.rb
class MostRankedPost < ApplicationRecord
  belongs_to :user
end

app/controllers/most_ranked_posts_controller.rb
class MostRankedPostsController < ApplicationController
  before_action :set_most_ranked_post, only: %i[ show edit update destroy ]

  # GET /most_ranked_posts or /most_ranked_posts.json
  def index
    @most_ranked_posts = MostRankedPost.all
  end

  # GET /most_ranked_posts/1 or /most_ranked_posts/1.json
  def show
  end

  # GET /most_ranked_posts/new
  def new
    @most_ranked_post = MostRankedPost.new
  end

  # GET /most_ranked_posts/1/edit
  def edit
  end

  # POST /most_ranked_posts or /most_ranked_posts.json
  def create
    @most_ranked_post = MostRankedPost.new(most_ranked_post_params)

    respond_to do |format|
      if @most_ranked_post.save
        format.html { redirect_to most_ranked_post_url(@most_ranked_post), notice: "Most ranked post was successfully created." }
        format.json { render :show, status: :created, location: @most_ranked_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @most_ranked_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /most_ranked_posts/1 or /most_ranked_posts/1.json
  def update
    respond_to do |format|
      if @most_ranked_post.update(most_ranked_post_params)
        format.html { redirect_to most_ranked_post_url(@most_ranked_post), notice: "Most ranked post was successfully updated." }
        format.json { render :show, status: :ok, location: @most_ranked_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @most_ranked_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /most_ranked_posts/1 or /most_ranked_posts/1.json
  def destroy
    @most_ranked_post.destroy

    respond_to do |format|
      format.html { redirect_to most_ranked_posts_url, notice: "Most ranked post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_most_ranked_post
      @most_ranked_post = MostRankedPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def most_ranked_post_params
      params.require(:most_ranked_post).permit(:user_id, :posts_id)
    end
end

app/helpers/most_ranked_posts_helper.rb
module MostRankedPostsHelper
end

app/views/most_ranked_posts/_form.html.erb
<%= form_with(model: most_ranked_post) do |form| %>
  <% if most_ranked_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(most_ranked_post.errors.count, "error") %> prohibited this most_ranked_post from being saved:</h2>

      <ul>
        <% most_ranked_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :posts_id %>
    <%= form.text_field :posts_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/most_ranked_posts/edit.html.erb
<h1>Editing Most Ranked Post</h1>

<%= render 'form', most_ranked_post: @most_ranked_post %>

<%= link_to 'Show', @most_ranked_post %> |
<%= link_to 'Back', most_ranked_posts_path %>

app/views/most_ranked_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Most Ranked Posts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Posts</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @most_ranked_posts.each do |most_ranked_post| %>
      <tr>
        <td><%= most_ranked_post.user_id %></td>
        <td><%= most_ranked_post.posts_id %></td>
        <td><%= link_to 'Show', most_ranked_post %></td>
        <td><%= link_to 'Edit', edit_most_ranked_post_path(most_ranked_post) %></td>
        <td><%= link_to 'Destroy', most_ranked_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Most Ranked Post', new_most_ranked_post_path %>

app/views/most_ranked_posts/new.html.erb
<h1>New Most Ranked Post</h1>

<%= render 'form', most_ranked_post: @most_ranked_post %>

<%= link_to 'Back', most_ranked_posts_path %>

app/views/most_ranked_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @most_ranked_post.user_id %>
</p>

<p>
  <strong>Posts:</strong>
  <%= @most_ranked_post.posts_id %>
</p>

<%= link_to 'Edit', edit_most_ranked_post_path(@most_ranked_post) %> |
<%= link_to 'Back', most_ranked_posts_path %>